/**
 * File Exporter - Handles downloading and exporting generated files
 */

import type { GeneratedFile } from "@/components/FileTree";

/**
 * Download a single file
 */
export function downloadFile(file: GeneratedFile): void {
  const blob = new Blob([file.content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = file.name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Download all files as a ZIP
 * Uses JSZip library (needs to be installed)
 */
export async function downloadAllAsZip(
  files: GeneratedFile[],
  projectName: string = "project"
): Promise<void> {
  // Dynamic import of JSZip
  const JSZip = (await import("jszip")).default;
  
  const zip = new JSZip();
  
  // Add each file to the zip
  for (const file of files) {
    zip.file(file.name, file.content);
  }
  
  // Add a README with project info
  const readme = generateReadme(files, projectName);
  zip.file("README.md", readme);
  
  // Generate and download the zip
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${projectName.replace(/\s+/g, "-").toLowerCase()}-instructions.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generate a README for the zip
 */
function generateReadme(files: GeneratedFile[], projectName: string): string {
  return `# ${projectName} - AI Instruction Files

This package contains AI instruction files generated by IntentCompiler.

## Files

${files.map(f => `- **${f.name}** - ${f.type} (Quality: ${f.quality}%)`).join("\n")}

## Usage

These instruction files are designed for use with AI assistants like Claude, Cursor, or other AI tools.

### For Single File Projects
1. Place the instruction file in your project root
2. The AI assistant will automatically read these instructions

### For Multi-File Projects
1. Review all files to understand the complete system
2. Start with the Architecture file if present
3. Implement each domain following its specific file
4. Use the Deployment file for production setup

## Quality Scores

${files.map(f => `- ${f.name}: ${f.quality}% ${f.quality >= 90 ? "✓" : f.quality >= 70 ? "⚠" : "✗"}`).join("\n")}

## Generated

Date: ${new Date().toLocaleString()}
Tool: IntentCompiler

---

*Transform your intent into structured AI instructions*
`;
}

/**
 * Copy all files content to clipboard
 */
export async function copyAllFiles(files: GeneratedFile[]): Promise<void> {
  const content = files
    .map(f => `=== ${f.name} ===\n\n${f.content}`)
    .join("\n\n" + "=".repeat(40) + "\n\n");
  
  await navigator.clipboard.writeText(content);
}

/**
 * Export files as JSON
 */
export function exportAsJson(files: GeneratedFile[]): string {
  return JSON.stringify(
    {
      generated: new Date().toISOString(),
      files: files.map(f => ({
        name: f.name,
        type: f.type,
        content: f.content,
        quality: f.quality,
        dependencies: f.dependencies
      }))
    },
    null,
    2
  );
}

/**
 * Import files from JSON
 */
export function importFromJson(json: string): GeneratedFile[] {
  try {
    const data = JSON.parse(json);
    if (!Array.isArray(data.files)) {
      throw new Error("Invalid format: missing files array");
    }
    
    return data.files.map((f: Record<string, unknown>) => ({
      name: String(f.name),
      type: String(f.type),
      content: String(f.content),
      quality: Number(f.quality) || 0,
      dependencies: Array.isArray(f.dependencies) 
        ? f.dependencies.map(String) 
        : []
    }));
  } catch (error) {
    throw new Error(`Failed to import files: ${error instanceof Error ? error.message : "Unknown error"}`);
  }
}
